apply plugin: 'com.android.application'

def buildWithCMake = project.hasProperty('BUILD_WITH_CMAKE')

android {
    namespace = "org.libsdl.app"
    compileSdkVersion 35
    defaultConfig {
        applicationId "com.frogzalcoatl.platformer"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "0.1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    if (!project.hasProperty('EXCLUDE_NATIVE_LIBS')) {
        sourceSets.main {
            jniLibs.srcDir 'libs'
        }
    }
    lint {
        abortOnError = false
        quiet = true
        ignoreWarnings = true
    }
    aaptOptions {
        noCompress 'dat', 'ogg', 'wav', 'ttf'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:none" << "-nowarn"
}