apply plugin: 'com.android.application'

def buildWithCMake = project.hasProperty('BUILD_WITH_CMAKE')

android {
    namespace = "org.libsdl.app"
    compileSdkVersion 35
    defaultConfig {
        applicationId "com.frogzalcoatl.platformer"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "0.1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    if (!project.hasProperty('EXCLUDE_NATIVE_LIBS')) {
        sourceSets.main {
            jniLibs.srcDir 'libs'
        }
    }
    lint {
        abortOnError = false
    }
    aaptOptions {
        noCompress 'dat', 'ogg', 'wav', 'ttf'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}

tasks.register('cmakeCopyAssets', Exec) {
    group = 'build'
    description = 'Executes the CMake preset build with copy_assets target'
    workingDir '../../' // Moves up to your root directory where CMakeLists.txt is

    if (System.getProperty('os.name').toLowerCase().contains('windows')) {
        commandLine 'cmd', '/c', 'cmake --build --preset android-arm64-debug --target copy_assets'
    } else {
        commandLine 'sh', '-c', 'cmake --build --preset android-arm64-debug --target copy_assets'
    }
}

tasks.register('cmakePackAssets', Exec) {
    group = 'build'
    description = 'Executes the CMake preset build with pack_assets target'
    workingDir '../../'

    if (System.getProperty('os.name').toLowerCase().contains('windows')) {
        commandLine 'cmd', '/c', 'cmake --build --preset android-arm64-debug --target pack_assets'
    } else {
        commandLine 'sh', '-c', 'cmake --build --preset android-arm64-debug --target pack_assets'
    }
}
